address: 0.0.0.0:7373

log:
  error: on
  audit: on

admin:
  identity: disable

tls:
  key: /etc/kes/cert/root.key
  cert: /etc/kes/cert/root.crt

policy:
  my-app:
    allow:
      - /v1/key/*/*
      - /v1/identity/*/*
      - /v1/policy/*/*
    identities:
      - f56ff90af3825d916b5903bc47a82b5c29c94702ff43e08cc1a02ece7f6f1d2d

keystore:
  fs:
    path: ./keys